[package]
name = "crabrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
url = "*"
fs2 = "*"
memchr = "*"
sha2 = "*"

[profile.release]
debug = 1
